export const ZODIAC_SIGNS = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces",
];

export const ORDER_SPECIES = [
  "Basilisk",
  "Eagle",
  "Centaur",
  "Cerberus",
  "Cyclops",
  "Dragon",
  "Griffin",
  "Harpy",
  "Hydra",
  "Kraken",
  "Medusa",
  "Minotaur",
  "Lion",
  "Pegasus",
  "Phoenix",
  "Tiberian Rat",
  "Vampire",
  "Werewolf",
];

export const BACKGROUNDS = [
  "academy-survivor",
  "awakened-late",
  "celestial-heir",
  "celestial-outcast",
  "shadow-influenced",
  "shadow-initiate",
  "star-bound",
  "royal",
  "benevolent-nymph",
  "oracle-sister",
];

export const BACKGROUND_LABELS: Record<string, string> = {
  "academy-survivor": "Survivor",
  "awakened-late": "Awakened",
  "celestial-heir": "Heir",
  "celestial-outcast": "Outcast",
  "shadow-influenced": "Shadow",
  "shadow-initiate": "Initiate",
  "star-bound": "Starborn",
  royal: "Royal",
  "benevolent-nymph": "Nymph",
  "oracle-sister": "Oracle",
};
